In [329]:
!pip install scikit-learn
!pip install seaborn matplotlib

Requirement already satisfied: scikit-learn in c:\users\usuario\appdata\local\programs\python\python313\lib\site-packages (1.9.0)
Requirement already satisfied: numpy>=1.24.1 in c:\users\usuario\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (2.4.6)
Requirement already satisfied: scipy>=1.10.0 in c:\users\usuario\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (1.18.0)
Requirement already satisfied: joblib>=1.4.0 in c:\users\usuario\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: narwhals>=2.0.1 in c:\users\usuario\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (2.22.1)
Requirement already satisfied: threadpoolctl>=3.5.0 in c:\users\usuario\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (3.6.0)

[notice] A new release of pip is available: 24.3.1 -> 26.1.2
[notice] To update, run: C:\Users\usuario\AppData\Local\Programs\Python\Python313\python.exe -m pip install --upgrade pip

Requirement already satisfied: seaborn in c:\users\usuario\appdata\local\programs\python\python313\lib\site-packages (0.13.2)
Requirement already satisfied: matplotlib in c:\users\usuario\appdata\local\programs\python\python313\lib\site-packages (3.10.9)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in c:\users\usuario\appdata\local\programs\python\python313\lib\site-packages (from seaborn) (2.4.6)
Requirement already satisfied: pandas>=1.2 in c:\users\usuario\appdata\local\programs\python\python313\lib\site-packages (from seaborn) (3.0.3)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\usuario\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\usuario\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\usuario\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\usuario\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in c:\users\usuario\appdata\roaming\python\python313\site-packages (from matplotlib) (26.2)
Requirement already satisfied: pillow>=8 in c:\users\usuario\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (12.2.0)
Requirement already satisfied: pyparsing>=3 in c:\users\usuario\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\usuario\appdata\roaming\python\python313\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\usuario\appdata\local\programs\python\python313\lib\site-packages (from pandas>=1.2->seaborn) (2026.2)
Requirement already satisfied: six>=1.5 in c:\users\usuario\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)

[notice] A new release of pip is available: 24.3.1 -> 26.1.2
[notice] To update, run: C:\Users\usuario\AppData\Local\Programs\Python\Python313\python.exe -m pip install --upgrade pip

In [330]:
import pandas as pd

wdi = pd.read_csv("wdi_panel.csv")
imf = pd.read_csv("imf_panel.csv")

In [331]:
wdi_countries = set(wdi["country_code"].unique())
imf_countries = set(imf["country_code"].unique())

print(f"WDI: {len(wdi_countries)} países")
print(f"FMI: {len(imf_countries)} países")

WDI: 117 países
FMI: 211 países

In [332]:
print("WDI:", wdi["year"].min(), "-", wdi["year"].max())
print("FMI:", imf["year"].min(), "-", imf["year"].max())

WDI: 2010 - 2025
FMI: 2010 - 2026

In [333]:
wdi_countries = set(wdi["country_code"].unique())
imf_countries = set(imf["country_code"].unique())

print(f"WDI: {len(wdi_countries)}")
print(f"FMI: {len(imf_countries)}")

WDI: 117
FMI: 211

In [334]:
test_merge = wdi.merge(
    imf,
    on=["country_code", "year"],
    how="left",
    indicator=True
)

test_merge["_merge"].value_counts()

_merge
both          1872
left_only        0
right_only       0
Name: count, dtype: int64

In [335]:
print("WDI:", wdi.shape)
print("Teste:", test_merge.shape)

WDI: (1872, 17)
Teste: (1872, 20)

In [336]:
panel_final = wdi.merge(
    imf,
    on=["country_code", "year"],
    how="left"
)

In [337]:
panel_final

,country_code,country,year,gdp_per_capita,real_gdp_growth,inflation_rate,compulsory_education_years,population_65_plus_pct,unemployment_rate,government_expenditure_pct_gdp,government_revenue_pct_gdp,gdp_deflator_inflation,age_dependency_ratio,gross_capital_formation_pct_gdp,total_reserves_months_imports,savings_pct_gdp,exports_pct_gdp,fiscal_balance_pct_gdp,gross_debt_pct_gdp
0,AFG,Afghanistan,2010,560.621505,14.362441,2.178538,9.0,2.306615,7.809,50.863005,11.091949,3.814630,103.144456,14.146241,10.457387,-2.737769,15.597470,0.933344,7.696949
1,AFG,Afghanistan,2011,606.694676,0.426355,11.804186,9.0,2.322140,7.830,59.484776,11.510161,16.593347,101.458308,14.146241,10.343973,-2.737769,15.597470,-0.671822,7.501084
2,AFG,Afghanistan,2012,651.417134,12.752287,6.441213,9.0,2.337911,7.875,42.329251,10.200625,7.301756,99.773131,14.146241,8.677209,-2.737769,15.597470,0.182057,6.759468
3,AFG,Afghanistan,2013,637.087099,5.600745,7.385772,9.0,2.349769,7.921,42.093684,9.405609,4.822785,98.063559,14.146241,8.588138,-2.737769,15.597470,-0.630946,6.904479
4,AFG,Afghanistan,2014,625.054942,2.724543,4.673996,9.0,2.356536,7.915,44.589299,8.613731,0.566945,96.346394,14.146241,10.702695,-2.737769,15.597470,-1.718797,8.700291
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1867,ZWE,Zimbabwe,2021,2613.605421,8.468017,98.546105,7.0,3.597974,9.540,19.077155,19.003463,108.772817,83.384953,13.456563,1.148220,42.874299,19.759617,-1.827539,39.891271
1868,ZWE,Zimbabwe,2022,2536.400502,6.139263,104.705171,7.0,3.608227,10.087,19.077155,19.003463,274.458090,82.547605,12.418930,0.704319,42.321958,23.699220,-0.999621,66.789092
1869,ZWE,Zimbabwe,2023,2195.224921,5.350869,3.466130,7.0,3.618322,9.348,19.077155,19.003463,768.477178,81.625352,10.023043,0.129141,12.072943,17.117076,-9.451342,76.127228
1870,ZWE,Zimbabwe,2024,2497.203322,1.742395,3.466130,7.0,3.601654,9.435,19.077155,19.003463,1097.246674,80.100412,8.846201,0.519375,10.700213,18.048842,-0.755905,70.380228
1871,ZWE,Zimbabwe,2025,2059.674454,4.734411,3.466130,7.0,3.387457,9.293,19.077155,19.003463,9.371075,86.516840,11.213924,0.656237,8.417171,21.987357,0.081812,43.765490

In [338]:
missing_pct = (
    panel_final
    .isna()
    .mean()
    .mul(100)
    .round(2)
    .sort_values(ascending=False)
)

print(missing_pct)

country_code                       0.0
country                            0.0
year                               0.0
gdp_per_capita                     0.0
real_gdp_growth                    0.0
inflation_rate                     0.0
compulsory_education_years         0.0
population_65_plus_pct             0.0
unemployment_rate                  0.0
government_expenditure_pct_gdp     0.0
government_revenue_pct_gdp         0.0
gdp_deflator_inflation             0.0
age_dependency_ratio               0.0
gross_capital_formation_pct_gdp    0.0
total_reserves_months_imports      0.0
savings_pct_gdp                    0.0
exports_pct_gdp                    0.0
fiscal_balance_pct_gdp             0.0
gross_debt_pct_gdp                 0.0
dtype: float64

In [339]:
panel_final

,country_code,country,year,gdp_per_capita,real_gdp_growth,inflation_rate,compulsory_education_years,population_65_plus_pct,unemployment_rate,government_expenditure_pct_gdp,government_revenue_pct_gdp,gdp_deflator_inflation,age_dependency_ratio,gross_capital_formation_pct_gdp,total_reserves_months_imports,savings_pct_gdp,exports_pct_gdp,fiscal_balance_pct_gdp,gross_debt_pct_gdp
0,AFG,Afghanistan,2010,560.621505,14.362441,2.178538,9.0,2.306615,7.809,50.863005,11.091949,3.814630,103.144456,14.146241,10.457387,-2.737769,15.597470,0.933344,7.696949
1,AFG,Afghanistan,2011,606.694676,0.426355,11.804186,9.0,2.322140,7.830,59.484776,11.510161,16.593347,101.458308,14.146241,10.343973,-2.737769,15.597470,-0.671822,7.501084
2,AFG,Afghanistan,2012,651.417134,12.752287,6.441213,9.0,2.337911,7.875,42.329251,10.200625,7.301756,99.773131,14.146241,8.677209,-2.737769,15.597470,0.182057,6.759468
3,AFG,Afghanistan,2013,637.087099,5.600745,7.385772,9.0,2.349769,7.921,42.093684,9.405609,4.822785,98.063559,14.146241,8.588138,-2.737769,15.597470,-0.630946,6.904479
4,AFG,Afghanistan,2014,625.054942,2.724543,4.673996,9.0,2.356536,7.915,44.589299,8.613731,0.566945,96.346394,14.146241,10.702695,-2.737769,15.597470,-1.718797,8.700291
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1867,ZWE,Zimbabwe,2021,2613.605421,8.468017,98.546105,7.0,3.597974,9.540,19.077155,19.003463,108.772817,83.384953,13.456563,1.148220,42.874299,19.759617,-1.827539,39.891271
1868,ZWE,Zimbabwe,2022,2536.400502,6.139263,104.705171,7.0,3.608227,10.087,19.077155,19.003463,274.458090,82.547605,12.418930,0.704319,42.321958,23.699220,-0.999621,66.789092
1869,ZWE,Zimbabwe,2023,2195.224921,5.350869,3.466130,7.0,3.618322,9.348,19.077155,19.003463,768.477178,81.625352,10.023043,0.129141,12.072943,17.117076,-9.451342,76.127228
1870,ZWE,Zimbabwe,2024,2497.203322,1.742395,3.466130,7.0,3.601654,9.435,19.077155,19.003463,1097.246674,80.100412,8.846201,0.519375,10.700213,18.048842,-0.755905,70.380228
1871,ZWE,Zimbabwe,2025,2059.674454,4.734411,3.466130,7.0,3.387457,9.293,19.077155,19.003463,9.371075,86.516840,11.213924,0.656237,8.417171,21.987357,0.081812,43.765490

In [340]:
problem_countries = (
    panel_final.loc[
        panel_final.drop(
            columns=["country", "country_code", "year"],
            errors="ignore"
        ).isna().any(axis=1),
        "country_code"
    ]
    .unique()
    .tolist()
)

print(problem_countries)

[]

In [341]:
panel_final = panel_final[
    ~panel_final["country_code"].isin(problem_countries)
].copy()

In [342]:
desc = panel_final.describe().T

print(desc)

                                  count          mean           std  \
year                             1872.0   2017.500000      4.611004
gdp_per_capita                   1872.0  18715.133675  23292.921081
real_gdp_growth                  1872.0      3.105191      4.895782
inflation_rate                   1872.0      6.629896     20.981916
compulsory_education_years       1872.0     10.069444      2.372677
population_65_plus_pct           1872.0     10.275435      6.501084
unemployment_rate                1872.0      8.049698      5.779575
government_expenditure_pct_gdp   1872.0     26.707003     10.622857
government_revenue_pct_gdp       1872.0     25.569577      9.800364
gdp_deflator_inflation           1872.0      8.316636     38.454580
age_dependency_ratio             1872.0     56.435028     14.638028
gross_capital_formation_pct_gdp  1872.0     23.954813      6.780378
total_reserves_months_imports    1872.0      4.862739      4.253273
savings_pct_gdp                  1872.0     22.741057      9.737576
exports_pct_gdp                  1872.0     44.011444     30.010191
fiscal_balance_pct_gdp           1872.0     -2.773013      4.457682
gross_debt_pct_gdp               1872.0     56.965264     34.792822

                                         min          25%          50%  \
year                             2010.000000  2013.750000  2017.500000
gdp_per_capita                    330.619413  3433.163945  7862.462990
real_gdp_growth                   -54.402093     1.509381     3.173953
inflation_rate                    -12.296984     1.539777     3.325319
compulsory_education_years          5.000000     9.000000    10.000000
population_65_plus_pct              1.421942     4.116546     8.373887
unemployment_rate                   0.249000     4.148000     6.326500
government_expenditure_pct_gdp      3.695458    17.792900    25.990627
government_revenue_pct_gdp          2.854992    18.092105    24.852918
gdp_deflator_inflation            -28.760135     1.613163     3.610943
age_dependency_ratio               21.769960    47.857883    53.310154
gross_capital_formation_pct_gdp     0.000000    19.785813    23.334982
total_reserves_months_imports       0.022138     2.065288     4.117117
savings_pct_gdp                   -21.782642    16.621414    21.937496
exports_pct_gdp                     0.720930    25.988137    37.097203
fiscal_balance_pct_gdp            -37.138836    -4.958742    -2.766156
gross_debt_pct_gdp                  0.000000    35.050855    49.808450

                                          75%            max
year                              2021.250000    2025.000000
gdp_per_capita                   26613.673008  137781.681659
real_gdp_growth                      5.115896      75.308418
inflation_rate                       6.217504     557.201817
compulsory_education_years          12.000000      16.000000
population_65_plus_pct              16.341578      24.624777
unemployment_rate                   10.274500      36.472000
government_expenditure_pct_gdp      34.457808      65.560022
government_revenue_pct_gdp          32.935731      56.338854
gdp_deflator_inflation               7.116572    1097.246674
age_dependency_ratio                61.190221     105.957237
gross_capital_formation_pct_gdp     27.154203      76.782325
total_reserves_months_imports        6.042288      37.373716
savings_pct_gdp                     28.367850      57.850180
exports_pct_gdp                     53.890495     222.308456
fiscal_balance_pct_gdp              -0.764675      26.974255
gross_debt_pct_gdp                  71.147840     345.522707

In [343]:
import sys

!{sys.executable} -m pip install --upgrade pip
!{sys.executable} -m pip install matplotlib seaborn

Requirement already satisfied: pip in c:\Users\usuario\AppData\Local\Programs\Python\Python311\Lib\site-packages (26.1.2)
Requirement already satisfied: matplotlib in c:\Users\usuario\AppData\Local\Programs\Python\Python311\Lib\site-packages (3.11.0)
Requirement already satisfied: seaborn in c:\Users\usuario\AppData\Local\Programs\Python\Python311\Lib\site-packages (0.13.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\Users\usuario\AppData\Local\Programs\Python\Python311\Lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\Users\usuario\AppData\Local\Programs\Python\Python311\Lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\Users\usuario\AppData\Local\Programs\Python\Python311\Lib\site-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\Users\usuario\AppData\Local\Programs\Python\Python311\Lib\site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: numpy>=1.25 in c:\Users\usuario\AppData\Local\Programs\Python\Python311\Lib\site-packages (from matplotlib) (2.4.6)
Requirement already satisfied: packaging>=20.0 in C:\Users\usuario\AppData\Roaming\Python\Python311\site-packages (from matplotlib) (26.2)
Requirement already satisfied: pillow>=9 in c:\Users\usuario\AppData\Local\Programs\Python\Python311\Lib\site-packages (from matplotlib) (12.2.0)
Requirement already satisfied: pyparsing>=3 in c:\Users\usuario\AppData\Local\Programs\Python\Python311\Lib\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in C:\Users\usuario\AppData\Roaming\Python\Python311\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: pandas>=1.2 in c:\Users\usuario\AppData\Local\Programs\Python\Python311\Lib\site-packages (from seaborn) (3.0.3)
Requirement already satisfied: tzdata in c:\Users\usuario\AppData\Local\Programs\Python\Python311\Lib\site-packages (from pandas>=1.2->seaborn) (2026.2)
Requirement already satisfied: six>=1.5 in C:\Users\usuario\AppData\Roaming\Python\Python311\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)

In [344]:
import matplotlib.pyplot as plt
import seaborn as sns

print(matplotlib.__version__)
print(seaborn.__version__)

3.11.0
0.13.2

In [346]:
id_cols = ["country", "country_code", "year"]

features = [
    c for c in panel_final.columns
    if c not in id_cols
]

In [347]:
features

['gdp_per_capita',
 'real_gdp_growth',
 'inflation_rate',
 'compulsory_education_years',
 'population_65_plus_pct',
 'unemployment_rate',
 'government_expenditure_pct_gdp',
 'government_revenue_pct_gdp',
 'gdp_deflator_inflation',
 'age_dependency_ratio',
 'gross_capital_formation_pct_gdp',
 'total_reserves_months_imports',
 'savings_pct_gdp',
 'exports_pct_gdp',
 'fiscal_balance_pct_gdp',
 'gross_debt_pct_gdp']

In [348]:
panel_final.to_csv(
    "df_model.csv",
    index=False
)

PCA

In [349]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X = scaler.fit_transform(
    panel_final[features]
)

In [350]:
from sklearn.decomposition import PCA

pca = PCA(n_components=7)

X_pca = pca.fit_transform(X)

In [351]:
import pandas as pd
import numpy as np

explained = pd.DataFrame({
    "PC": np.arange(1, pca.n_components_ + 1),
    "Explained_Variance": pca.explained_variance_ratio_,
    "Cumulative": pca.explained_variance_ratio_.cumsum()
})


print(explained)

   PC  Explained_Variance  Cumulative
0   1            0.221047    0.221047
1   2            0.158038    0.379086
2   3            0.096485    0.475570
3   4            0.079053    0.554623
4   5            0.072497    0.627119
5   6            0.066944    0.694063
6   7            0.053978    0.748042

In [352]:
panel_final["fiscal_risk_index"] = X_pca[:, 0]

In [353]:
loadings = pd.DataFrame(
    pca.components_.T,
    index=features,
    columns=[f"PC{i+1}" for i in range(pca.n_components_)]
)

print(loadings)

                                      PC1       PC2       PC3       PC4  \
gdp_per_capita                   0.362960  0.209088  0.218937  0.055278
real_gdp_growth                 -0.121507  0.278128 -0.001629 -0.137697
inflation_rate                  -0.115457 -0.214067  0.593230  0.037800
compulsory_education_years       0.199745 -0.051568 -0.023545  0.602713
population_65_plus_pct           0.449711 -0.033613  0.039528  0.005286
unemployment_rate                0.030508 -0.264198 -0.186255 -0.388347
government_expenditure_pct_gdp   0.422177 -0.221862 -0.132082 -0.111736
government_revenue_pct_gdp       0.434474 -0.025746 -0.033495 -0.212115
gdp_deflator_inflation          -0.103333 -0.176295  0.602760 -0.038984
age_dependency_ratio            -0.297289 -0.158178 -0.000524 -0.303899
gross_capital_formation_pct_gdp -0.125216  0.334086 -0.177638 -0.157138
total_reserves_months_imports   -0.104317  0.087416 -0.101137  0.479745
savings_pct_gdp                  0.012097  0.467265  0.141265 -0.100032
exports_pct_gdp                  0.292330  0.269236  0.180269 -0.203607
fiscal_balance_pct_gdp           0.046599  0.358365  0.275152 -0.059757
gross_debt_pct_gdp               0.129239 -0.339149  0.107246 -0.034883

                                      PC5       PC6       PC7
gdp_per_capita                  -0.131076  0.068743 -0.183202
real_gdp_growth                 -0.005095  0.441717  0.213821
inflation_rate                   0.047994 -0.151883  0.162022
compulsory_education_years      -0.045543  0.139911  0.327587
population_65_plus_pct           0.000924  0.053316  0.233918
unemployment_rate                0.314789 -0.317957 -0.170726
government_expenditure_pct_gdp   0.190758  0.004126  0.248278
government_revenue_pct_gdp       0.326461 -0.039410  0.228407
gdp_deflator_inflation           0.092496 -0.107934  0.216469
age_dependency_ratio             0.160495  0.281924  0.185119
gross_capital_formation_pct_gdp -0.239014 -0.397591  0.527990
total_reserves_months_imports    0.481806 -0.368362 -0.174871
savings_pct_gdp                  0.016905 -0.416910  0.134603
exports_pct_gdp                 -0.211481 -0.034105 -0.374226
fiscal_balance_pct_gdp           0.449969  0.223133 -0.141335
gross_debt_pct_gdp              -0.406566 -0.205771 -0.144418

In [354]:
pca = PCA(n_components=6)

X_pca = pca.fit_transform(X)

In [355]:

weights = (
    pca.explained_variance_ratio_
    / pca.explained_variance_ratio_.sum()
)

panel_final["fiscal_risk_index"] = (
    X_pca * weights
).sum(axis=1)

In [356]:
weights

array([0.31848306, 0.2277002 , 0.13901421, 0.11389819, 0.10445241,
       0.09645194])

In [357]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler(feature_range=(0, 100))

panel_final["fiscal_risk_index_100"] = (
    scaler.fit_transform(
        panel_final[["fiscal_risk_index"]]
    )
)

In [358]:
panel_final

,country_code,country,year,gdp_per_capita,real_gdp_growth,inflation_rate,compulsory_education_years,population_65_plus_pct,unemployment_rate,government_expenditure_pct_gdp,...,gdp_deflator_inflation,age_dependency_ratio,gross_capital_formation_pct_gdp,total_reserves_months_imports,savings_pct_gdp,exports_pct_gdp,fiscal_balance_pct_gdp,gross_debt_pct_gdp,fiscal_risk_index,fiscal_risk_index_100
0,AFG,Afghanistan,2010,560.621505,14.362441,2.178538,9.0,2.306615,7.809,50.863005,...,3.814630,103.144456,14.146241,10.457387,-2.737769,15.597470,0.933344,7.696949,-0.573595,30.047967
1,AFG,Afghanistan,2011,606.694676,0.426355,11.804186,9.0,2.322140,7.830,59.484776,...,16.593347,101.458308,14.146241,10.343973,-2.737769,15.597470,-0.671822,7.501084,-0.712176,27.391958
2,AFG,Afghanistan,2012,651.417134,12.752287,6.441213,9.0,2.337911,7.875,42.329251,...,7.301756,99.773131,14.146241,8.677209,-2.737769,15.597470,0.182057,6.759468,-0.682774,27.955465
3,AFG,Afghanistan,2013,637.087099,5.600745,7.385772,9.0,2.349769,7.921,42.093684,...,4.822785,98.063559,14.146241,8.588138,-2.737769,15.597470,-0.630946,6.904479,-0.793906,25.825520
4,AFG,Afghanistan,2014,625.054942,2.724543,4.673996,9.0,2.356536,7.915,44.589299,...,0.566945,96.346394,14.146241,10.702695,-2.737769,15.597470,-1.718797,8.700291,-0.834038,25.056357
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1867,ZWE,Zimbabwe,2021,2613.605421,8.468017,98.546105,7.0,3.597974,9.540,19.077155,...,108.772817,83.384953,13.456563,1.148220,42.874299,19.759617,-1.827539,39.891271,-0.594833,29.640921
1868,ZWE,Zimbabwe,2022,2536.400502,6.139263,104.705171,7.0,3.608227,10.087,19.077155,...,274.458090,82.547605,12.418930,0.704319,42.321958,23.699220,-0.999621,66.789092,-0.614405,29.265812
1869,ZWE,Zimbabwe,2023,2195.224921,5.350869,3.466130,7.0,3.618322,9.348,19.077155,...,768.477178,81.625352,10.023043,0.129141,12.072943,17.117076,-9.451342,76.127228,-1.145085,19.094890
1870,ZWE,Zimbabwe,2024,2497.203322,1.742395,3.466130,7.0,3.601654,9.435,19.077155,...,1097.246674,80.100412,8.846201,0.519375,10.700213,18.048842,-0.755905,70.380228,-0.715654,27.325299
1871,ZWE,Zimbabwe,2025,2059.674454,4.734411,3.466130,7.0,3.387457,9.293,19.077155,...,9.371075,86.516840,11.213924,0.656237,8.417171,21.987357,0.081812,43.765490,-0.821236,25.301735

In [359]:
panel_final.loc[
    panel_final["country"] == "Brazil",
    ["year", "fiscal_risk_index_100"]
].sort_values("year")

     year  fiscal_risk_index_100
240  2010              35.896249
241  2011              37.121014
242  2012              37.378735
243  2013              42.814108
244  2014              39.740233
245  2015              37.053290
246  2016              37.540094
247  2017              37.271084
248  2018              38.140663
249  2019              39.516344
250  2020              32.217072
251  2021              41.353360
252  2022              42.444397
253  2023              40.240061
254  2024              41.481027
255  2025              38.635423

In [360]:
panel_final.to_csv(
    "fiscal_risk_index.csv",
    index=False
)

In [361]:
pc_scores = pd.DataFrame(
    X_pca,
    columns=[f"PC{i+1}" for i in range(6)]
)

pc_scores["country"] = panel_final["country"]
pc_scores["year"] = panel_final["year"]

In [362]:
pc_scores.loc[
    pc_scores["country"] == "Brazil"
]

          PC1       PC2       PC3       PC4       PC5       PC6 country  year
240 -0.759909 -0.311566 -0.517804  0.438647  0.776579 -0.151233  Brazil  2010
241 -0.597123 -0.345852 -0.380939  0.617207  0.866878 -0.451174  Brazil  2011
242 -0.539974 -0.444847 -0.412546  0.836368  1.014247 -0.639602  Brazil  2012
243 -0.095937 -0.545539 -0.509819  2.332553  0.711947 -0.227047  Brazil  2013
244 -0.044495 -1.101296 -0.676127  2.554153  0.415781 -0.448979  Brazil  2014
245  0.288426 -2.057689 -0.916604  2.941921  0.728621 -1.194082  Brazil  2015
246  0.341654 -2.260303 -0.911994  2.998434  1.268441 -1.286152  Brazil  2016
247  0.265911 -2.038195 -1.068271  2.641636  0.974981 -0.741541  Brazil  2017
248  0.363199 -1.980789 -0.947153  2.419107  0.838683 -0.492084  Brazil  2018
249  0.403666 -1.851965 -0.782431  2.321782  0.875920 -0.348452  Brazil  2019
250  0.423812 -2.686752 -1.289607  2.686817  0.433937 -1.614256  Brazil  2020
251  0.230361 -1.154036 -0.372635  1.840527  0.829672 -0.402345  Brazil  2021
252  0.553975 -1.351604 -0.317788  1.837645  0.368995  0.008940  Brazil  2022
253  0.537138 -1.673543 -0.672860  2.183772  0.075569  0.052900  Brazil  2023
254  0.598271 -1.510028 -0.553828  2.029171 -0.060601  0.294799  Brazil  2024
255  0.278446 -1.690095 -0.663542  2.570159  0.012918 -0.323724  Brazil  2025