In [78]:
pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\users\usuario\appdata\local\programs\python\python311\lib\site-packages (1.9.0)
Requirement already satisfied: numpy>=1.24.1 in c:\users\usuario\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn) (2.4.6)
Requirement already satisfied: scipy>=1.10.0 in c:\users\usuario\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.4.0 in c:\users\usuario\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: narwhals>=2.0.1 in c:\users\usuario\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn) (2.22.1)
Requirement already satisfied: threadpoolctl>=3.5.0 in c:\users\usuario\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn) (3.6.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [79]:
import pandas as pd

wdi = pd.read_csv("wdi_panel.csv")
imf = pd.read_csv("imf_panel.csv")

In [80]:
wdi_countries = set(wdi["country_code"].unique())
imf_countries = set(imf["country_code"].unique())

print(f"WDI: {len(wdi_countries)} países")
print(f"FMI: {len(imf_countries)} países")

WDI: 118 países
FMI: 205 países

In [81]:
print("WDI:", wdi["year"].min(), "-", wdi["year"].max())
print("FMI:", imf["year"].min(), "-", imf["year"].max())

WDI: 2010 - 2025
FMI: 2010 - 2026

In [82]:
wdi_countries = set(wdi["country_code"].unique())
imf_countries = set(imf["country_code"].unique())

print(f"WDI: {len(wdi_countries)}")
print(f"FMI: {len(imf_countries)}")

WDI: 118
FMI: 205

In [83]:
test_merge = wdi.merge(
    imf,
    on=["country_code", "year"],
    how="left",
    indicator=True
)

test_merge["_merge"].value_counts()

_merge
both          1856
left_only       32
right_only       0
Name: count, dtype: int64

In [84]:
print("WDI:", wdi.shape)
print("Teste:", test_merge.shape)

WDI: (1888, 19)
Teste: (1888, 23)

In [85]:
panel_final = wdi.merge(
    imf,
    on=["country_code", "year"],
    how="left"
)

In [86]:
panel_final

,country_code,country,year,gdp_per_capita,real_gdp_growth,inflation_rate,compulsory_education_years,population_65_plus_pct,fertility_rate,unemployment_rate,...,gdp_deflator_inflation,current_account_pct_gdp,age_dependency_ratio,gross_capital_formation_pct_gdp,total_reserves_months_imports,savings_pct_gdp,exports_pct_gdp,fiscal_balance_pct_gdp,gross_debt_pct_gdp,primary_balance_pct_gdp
0,AFG,Afghanistan,2010,560.621505,14.362441,2.178538,9.0,2.306615,6.195,7.809,...,3.814630,-3.643314,103.144456,14.146241,10.457387,-2.737769,15.597470,0.933344,7.696949,0.944992
1,AFG,Afghanistan,2011,606.694676,0.426355,11.804186,9.0,2.322140,6.094,7.830,...,16.593347,-12.619538,101.458308,14.146241,10.343973,-2.737769,15.597470,-0.671822,7.501084,-0.573311
2,AFG,Afghanistan,2012,651.417134,12.752287,6.441213,9.0,2.337911,5.985,7.875,...,7.301756,-25.870681,99.773131,14.146241,8.677209,-2.737769,15.597470,0.182057,6.759468,0.257318
3,AFG,Afghanistan,2013,637.087099,5.600745,7.385772,9.0,2.349769,5.879,7.921,...,4.822785,-25.290059,98.063559,14.146241,8.588138,-2.737769,15.597470,-0.630946,6.904479,-0.543948
4,AFG,Afghanistan,2014,625.054942,2.724543,4.673996,9.0,2.356536,5.770,7.915,...,0.566945,-15.772420,96.346394,14.146241,10.702695,-2.737769,15.597470,-1.718797,8.700291,-1.685043
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1883,ZWE,Zimbabwe,2021,2613.605421,8.468017,98.546105,7.0,3.597974,3.765,9.540,...,108.772817,0.843388,83.384953,13.456563,1.148220,42.874299,19.759617,-1.827539,39.891271,-1.356460
1884,ZWE,Zimbabwe,2022,2536.400502,6.139263,104.705171,7.0,3.608227,3.767,10.087,...,274.458090,0.748243,82.547605,12.418930,0.704319,42.321958,23.699220,-0.999621,66.789092,-0.941907
1885,ZWE,Zimbabwe,2023,2195.224921,5.350869,3.466130,7.0,3.618322,3.724,9.348,...,768.477178,0.373211,81.625352,10.023043,0.129141,12.072943,17.117076,-9.451342,76.127228,-9.152526
1886,ZWE,Zimbabwe,2024,2497.203322,1.742395,3.466130,7.0,3.601654,3.674,9.435,...,1097.246674,1.206567,80.100412,8.846201,0.519375,10.700213,18.048842,-0.755905,70.380228,0.077595
1887,ZWE,Zimbabwe,2025,2059.674454,4.734411,3.466130,7.0,3.387457,3.768,9.293,...,9.371075,-3.392393,86.516840,11.213924,0.656237,8.417171,21.987357,0.081812,43.765490,0.698125

In [87]:
missing_pct = (
    panel_final
    .isna()
    .mean()
    .mul(100)
    .round(2)
    .sort_values(ascending=False)
)

print(missing_pct)

fiscal_balance_pct_gdp             1.69
primary_balance_pct_gdp            1.69
gross_debt_pct_gdp                 1.69
year                               0.00
country_code                       0.00
country                            0.00
inflation_rate                     0.00
real_gdp_growth                    0.00
gdp_per_capita                     0.00
compulsory_education_years         0.00
government_expenditure_pct_gdp     0.00
population_65_plus_pct             0.00
fertility_rate                     0.00
unemployment_rate                  0.00
current_account_pct_gdp            0.00
gdp_deflator_inflation             0.00
government_revenue_pct_gdp         0.00
age_dependency_ratio               0.00
savings_pct_gdp                    0.00
total_reserves_months_imports      0.00
gross_capital_formation_pct_gdp    0.00
exports_pct_gdp                    0.00
dtype: float64

In [89]:
panel_final

,country_code,country,year,gdp_per_capita,real_gdp_growth,inflation_rate,compulsory_education_years,population_65_plus_pct,fertility_rate,unemployment_rate,...,gdp_deflator_inflation,current_account_pct_gdp,age_dependency_ratio,gross_capital_formation_pct_gdp,total_reserves_months_imports,savings_pct_gdp,exports_pct_gdp,fiscal_balance_pct_gdp,gross_debt_pct_gdp,primary_balance_pct_gdp
0,AFG,Afghanistan,2010,560.621505,14.362441,2.178538,9.0,2.306615,6.195,7.809,...,3.814630,-3.643314,103.144456,14.146241,10.457387,-2.737769,15.597470,0.933344,7.696949,0.944992
1,AFG,Afghanistan,2011,606.694676,0.426355,11.804186,9.0,2.322140,6.094,7.830,...,16.593347,-12.619538,101.458308,14.146241,10.343973,-2.737769,15.597470,-0.671822,7.501084,-0.573311
2,AFG,Afghanistan,2012,651.417134,12.752287,6.441213,9.0,2.337911,5.985,7.875,...,7.301756,-25.870681,99.773131,14.146241,8.677209,-2.737769,15.597470,0.182057,6.759468,0.257318
3,AFG,Afghanistan,2013,637.087099,5.600745,7.385772,9.0,2.349769,5.879,7.921,...,4.822785,-25.290059,98.063559,14.146241,8.588138,-2.737769,15.597470,-0.630946,6.904479,-0.543948
4,AFG,Afghanistan,2014,625.054942,2.724543,4.673996,9.0,2.356536,5.770,7.915,...,0.566945,-15.772420,96.346394,14.146241,10.702695,-2.737769,15.597470,-1.718797,8.700291,-1.685043
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1883,ZWE,Zimbabwe,2021,2613.605421,8.468017,98.546105,7.0,3.597974,3.765,9.540,...,108.772817,0.843388,83.384953,13.456563,1.148220,42.874299,19.759617,-1.827539,39.891271,-1.356460
1884,ZWE,Zimbabwe,2022,2536.400502,6.139263,104.705171,7.0,3.608227,3.767,10.087,...,274.458090,0.748243,82.547605,12.418930,0.704319,42.321958,23.699220,-0.999621,66.789092,-0.941907
1885,ZWE,Zimbabwe,2023,2195.224921,5.350869,3.466130,7.0,3.618322,3.724,9.348,...,768.477178,0.373211,81.625352,10.023043,0.129141,12.072943,17.117076,-9.451342,76.127228,-9.152526
1886,ZWE,Zimbabwe,2024,2497.203322,1.742395,3.466130,7.0,3.601654,3.674,9.435,...,1097.246674,1.206567,80.100412,8.846201,0.519375,10.700213,18.048842,-0.755905,70.380228,0.077595
1887,ZWE,Zimbabwe,2025,2059.674454,4.734411,3.466130,7.0,3.387457,3.768,9.293,...,9.371075,-3.392393,86.516840,11.213924,0.656237,8.417171,21.987357,0.081812,43.765490,0.698125

In [90]:
problem_countries = (
    panel_final.loc[
        panel_final.drop(
            columns=["country", "country_code", "year"],
            errors="ignore"
        ).isna().any(axis=1),
        "country_code"
    ]
    .unique()
    .tolist()
)

print(problem_countries)

['WSM', 'SGP']

In [91]:
panel_final = panel_final[
    ~panel_final["country_code"].isin(problem_countries)
].copy()

In [92]:
desc = panel_final.describe().T

print(desc)

                                  count          mean           std  \
year                             1856.0   2017.500000      4.611015
gdp_per_capita                   1856.0  18288.499700  22967.076468
real_gdp_growth                  1856.0      3.097215      5.020666
inflation_rate                   1856.0      6.684661     21.067020
compulsory_education_years       1856.0     10.113147      2.346557
population_65_plus_pct           1856.0     10.277347      6.525746
fertility_rate                   1856.0      2.358146      1.145310
unemployment_rate                1856.0      8.050863      5.807220
government_expenditure_pct_gdp   1856.0     27.101094     11.158101
government_revenue_pct_gdp       1856.0     26.467236     16.777138
gdp_deflator_inflation           1856.0      8.401903     38.640584
current_account_pct_gdp          1856.0     -1.281641     12.785864
age_dependency_ratio             1856.0     56.656911     14.482446
gross_capital_formation_pct_gdp  1856.0     23.969448      6.949394
total_reserves_months_imports    1856.0      4.862477      4.268558
savings_pct_gdp                  1856.0     23.050290     14.920543
exports_pct_gdp                  1856.0     42.713098     27.257557
fiscal_balance_pct_gdp           1856.0     -3.100421      5.255422
gross_debt_pct_gdp               1856.0     56.055965     34.546401
primary_balance_pct_gdp          1856.0     -1.343324      4.983215

                                         min          25%          50%  \
year                             2010.000000  2013.750000  2017.500000
gdp_per_capita                    330.619413  3278.954176  7763.778055
real_gdp_growth                   -54.402093     1.509381     3.168742
inflation_rate                    -12.296984     1.563744     3.340098
compulsory_education_years          5.000000     9.000000    10.000000
population_65_plus_pct              1.421942     4.095921     8.299094
fertility_rate                      0.582000     1.539750     1.923000
unemployment_rate                   0.249000     4.134000     6.309500
government_expenditure_pct_gdp      3.695458    18.064100    26.208614
government_revenue_pct_gdp          2.854992    18.092105    25.069294
gdp_deflator_inflation            -28.760135     1.637650     3.671889
current_account_pct_gdp           -43.771235    -5.471944    -2.136177
age_dependency_ratio               21.769960    48.067654    53.452950
gross_capital_formation_pct_gdp     0.000000    19.726747    23.306251
total_reserves_months_imports       0.022138     2.058816     4.079620
savings_pct_gdp                   -21.782642    16.545803    21.747819
exports_pct_gdp                     0.720930    25.401131    36.918466
fiscal_balance_pct_gdp            -55.749065    -5.066025    -2.816623
gross_debt_pct_gdp                  0.000000    34.513914    49.444076
primary_balance_pct_gdp           -55.749065    -2.915404    -1.102167

                                          75%            max
year                              2021.250000    2025.000000
gdp_per_capita                   25832.638564  137781.681659
real_gdp_growth                      5.133162      75.308418
inflation_rate                       6.272288     557.201817
compulsory_education_years          12.000000      16.000000
population_65_plus_pct              16.402674      24.624777
fertility_rate                       2.850000       6.587000
unemployment_rate                   10.295250      36.472000
government_expenditure_pct_gdp      34.854300      83.608026
government_revenue_pct_gdp          33.273184     344.999452
gdp_deflator_inflation               7.175446    1097.246674
current_account_pct_gdp              1.932132     235.750597
age_dependency_ratio                61.342370     105.957237
gross_capital_formation_pct_gdp     27.068648      76.782325
total_reserves_months_imports        6.080139      37.373716
savings_pct_gdp                     28.269894     332.918714
exports_pct_gdp                     53.059507     222.308456
fiscal_balance_pct_gdp              -0.871585      26.974255
gross_debt_pct_gdp                  70.652035     345.522707
primary_balance_pct_gdp              0.551552      26.974255

In [93]:
id_cols = ["country", "country_code", "year"]

features = [
    c for c in panel_final.columns
    if c not in id_cols
]

In [94]:
panel_final.to_csv(
    "df_model.csv",
    index=False
)

In [95]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X = scaler.fit_transform(
    panel_final[features]
)

In [109]:
from sklearn.decomposition import PCA

pca = PCA()

X_pca = pca.fit_transform(X)

In [110]:
import pandas as pd
import numpy as np

explained = pd.DataFrame({
    "PC": np.arange(1, len(features)+1),
    "Explained_Variance": pca.explained_variance_ratio_,
    "Cumulative": pca.explained_variance_ratio_.cumsum()
})

print(explained)

    PC  Explained_Variance  Cumulative
0    1            0.206204    0.206204
1    2            0.139259    0.345463
2    3            0.132915    0.478379
3    4            0.087968    0.566347
4    5            0.068479    0.634826
5    6            0.063579    0.698405
6    7            0.051046    0.749452
7    8            0.044616    0.794068
8    9            0.041046    0.835114
9   10            0.035075    0.870188
10  11            0.034200    0.904389
11  12            0.027921    0.932310
12  13            0.024119    0.956429
13  14            0.021404    0.977833
14  15            0.012421    0.990254
15  16            0.004238    0.994492
16  17            0.002089    0.996581
17  18            0.001900    0.998481
18  19            0.001519    1.000000

In [111]:
panel_final["fiscal_risk_index"] = X_pca[:, 0]

In [112]:
loadings = pd.DataFrame(
    pca.components_.T,
    index=features,
    columns=[f"PC{i+1}" for i in range(len(features))]
)

print(loadings)

                                      PC1       PC2       PC3       PC4  \
gdp_per_capita                  -0.347792 -0.036538  0.154204  0.079807
real_gdp_growth                  0.077464  0.159254  0.268723 -0.101263
inflation_rate                   0.118846 -0.099568 -0.079693  0.544643
compulsory_education_years      -0.216973 -0.143643  0.025420 -0.046955
population_65_plus_pct          -0.404464 -0.150667 -0.044759  0.046685
fertility_rate                   0.415025  0.180221 -0.046818  0.098430
unemployment_rate                0.024254 -0.107160 -0.179042  0.085308
government_expenditure_pct_gdp  -0.332481 -0.014595 -0.324028  0.038894
government_revenue_pct_gdp      -0.286916  0.363089 -0.222194  0.177339
gdp_deflator_inflation           0.105306 -0.066841 -0.059126  0.547821
current_account_pct_gdp         -0.201669  0.462069  0.012114  0.258524
age_dependency_ratio             0.339842  0.130282 -0.119823  0.171498
gross_capital_formation_pct_gdp  0.051419  0.327445  0.043155 -0.287700
total_reserves_months_imports    0.068573  0.076632  0.082831 -0.078326
savings_pct_gdp                 -0.122713  0.546773  0.031073  0.145699
exports_pct_gdp                 -0.294823 -0.000520  0.179683  0.002159
fiscal_balance_pct_gdp          -0.037868 -0.051019  0.551308  0.222616
gross_debt_pct_gdp              -0.061954 -0.288094 -0.245270  0.169291
primary_balance_pct_gdp         -0.026447 -0.106970  0.531341  0.218446

                                      PC5       PC6       PC7       PC8  \
gdp_per_capita                  -0.087201 -0.183474 -0.249025 -0.230290
real_gdp_growth                 -0.132094 -0.207072  0.086910  0.560175
inflation_rate                   0.246299 -0.222379  0.142883  0.000346
compulsory_education_years       0.394068  0.039035 -0.298215  0.459501
population_65_plus_pct          -0.103253 -0.027919 -0.082596  0.095992
fertility_rate                  -0.226497  0.045188 -0.272362 -0.042315
unemployment_rate               -0.314820  0.499343  0.547186  0.042094
government_expenditure_pct_gdp  -0.176052  0.153212 -0.132522  0.044802
government_revenue_pct_gdp      -0.094184  0.152915 -0.025902  0.126265
gdp_deflator_inflation           0.194255 -0.260165  0.158473 -0.075256
current_account_pct_gdp          0.061968  0.142399 -0.083621  0.006722
age_dependency_ratio            -0.330565  0.032935 -0.429257  0.064012
gross_capital_formation_pct_gdp  0.064239 -0.287993  0.386404  0.108102
total_reserves_months_imports    0.542357  0.479530 -0.022765 -0.247414
savings_pct_gdp                  0.098686 -0.005805  0.134240  0.065465
exports_pct_gdp                 -0.256041 -0.266236  0.138374 -0.395300
fiscal_balance_pct_gdp          -0.129302  0.202264 -0.008641  0.028297
gross_debt_pct_gdp              -0.046001 -0.024461  0.132952  0.349742
primary_balance_pct_gdp         -0.121651  0.243103  0.036389  0.157891

                                      PC9      PC10      PC11      PC12  \
gdp_per_capita                  -0.156572  0.092690  0.182546  0.399361
real_gdp_growth                  0.569906  0.017742  0.362802  0.183326
inflation_rate                   0.039854  0.103609 -0.041606  0.149230
compulsory_education_years      -0.045228 -0.289552 -0.485300  0.368546
population_65_plus_pct           0.019635  0.434539 -0.035276 -0.186999
fertility_rate                  -0.075125 -0.009754 -0.038427  0.289259
unemployment_rate                0.083126 -0.145462 -0.212408  0.304353
government_expenditure_pct_gdp   0.258868  0.313118 -0.084730  0.101394
government_revenue_pct_gdp       0.085152  0.099894 -0.015026 -0.054984
gdp_deflator_inflation           0.256785  0.103506 -0.139616 -0.031600
current_account_pct_gdp         -0.052444 -0.333579  0.135703 -0.137130
age_dependency_ratio            -0.078393  0.193496 -0.085061  0.190215
gross_capital_formation_pct_gdp -0.326195  0.454165 -0.265876  0.230837
total_reserves_months_imports    0.148920  0.303290  0.331683  0.344758
savings_pct_gdp                 -0.222420 -0.076788  0.010328 -0.004494
exports_pct_gdp                  0.124330 -0.272879 -0.001601  0.400078
fiscal_balance_pct_gdp          -0.101660  0.176909 -0.131650 -0.083310
gross_debt_pct_gdp              -0.505636 -0.045021  0.545955  0.160667
primary_balance_pct_gdp         -0.159719  0.083995 -0.034744 -0.057150

                                     PC13      PC14      PC15      PC16  \
gdp_per_capita                  -0.259938  0.492674 -0.386102  0.033272
real_gdp_growth                 -0.010485  0.111147  0.015534 -0.011672
inflation_rate                   0.660267  0.255685 -0.033693 -0.022568
compulsory_education_years      -0.046253 -0.056089  0.078733  0.046534
population_65_plus_pct          -0.034143  0.233479  0.610666  0.081303
fertility_rate                   0.001257 -0.105010 -0.028060 -0.064491
unemployment_rate               -0.135362  0.332776  0.052989  0.032403
government_expenditure_pct_gdp   0.113306 -0.284149 -0.265585 -0.585144
government_revenue_pct_gdp       0.115821 -0.220142 -0.289965  0.674135
gdp_deflator_inflation          -0.633111 -0.215145 -0.001176  0.006285
current_account_pct_gdp         -0.053181  0.105873  0.150497 -0.121864
age_dependency_ratio            -0.042172  0.036397  0.318502  0.090121
gross_capital_formation_pct_gdp -0.038024 -0.080973 -0.043401  0.021795
total_reserves_months_imports   -0.023733 -0.105657  0.175323  0.064945
savings_pct_gdp                 -0.040112  0.085274  0.158057 -0.353584
exports_pct_gdp                  0.173279 -0.410124  0.336184  0.073670
fiscal_balance_pct_gdp           0.049230 -0.083842 -0.087088  0.085607
gross_debt_pct_gdp              -0.074767 -0.268583  0.050904  0.012593
primary_balance_pct_gdp          0.037333 -0.199336 -0.085633 -0.147551

                                     PC17      PC18      PC19
gdp_per_capita                   0.018110 -0.034531 -0.057685
real_gdp_growth                  0.001083  0.018928  0.030876
inflation_rate                  -0.043096 -0.035029 -0.008033
compulsory_education_years       0.005147  0.036681  0.017408
population_65_plus_pct          -0.189751  0.243328 -0.161896
fertility_rate                  -0.404712  0.579353 -0.218579
unemployment_rate               -0.006806 -0.006006  0.011646
government_expenditure_pct_gdp  -0.025774 -0.045998  0.129984
government_revenue_pct_gdp       0.083544  0.050681 -0.160367
gdp_deflator_inflation          -0.012529  0.003652 -0.013032
current_account_pct_gdp         -0.551358 -0.281156  0.248712
age_dependency_ratio             0.300600 -0.463454  0.142216
gross_capital_formation_pct_gdp -0.263104 -0.177918  0.097764
total_reserves_months_imports    0.015988 -0.024996  0.000077
savings_pct_gdp                  0.555991  0.286647 -0.161364
exports_pct_gdp                  0.038111 -0.028662  0.002423
fiscal_balance_pct_gdp           0.089067  0.294598  0.631640
gross_debt_pct_gdp              -0.002292  0.050097  0.130652
primary_balance_pct_gdp         -0.088266 -0.312859 -0.587129

In [100]:
pca = PCA(n_components=7)

X_pca = pca.fit_transform(X)

In [101]:
weights = pca.explained_variance_ratio_

panel_final["fiscal_risk_index"] = (
    X_pca * weights
).sum(axis=1)

In [102]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler(feature_range=(0, 100))

panel_final["fiscal_risk_index_100"] = (
    scaler.fit_transform(
        panel_final[["fiscal_risk_index"]]
    )
)

In [103]:
panel_final

,country_code,country,year,gdp_per_capita,real_gdp_growth,inflation_rate,compulsory_education_years,population_65_plus_pct,fertility_rate,unemployment_rate,...,age_dependency_ratio,gross_capital_formation_pct_gdp,total_reserves_months_imports,savings_pct_gdp,exports_pct_gdp,fiscal_balance_pct_gdp,gross_debt_pct_gdp,primary_balance_pct_gdp,fiscal_risk_index,fiscal_risk_index_100
0,AFG,Afghanistan,2010,560.621505,14.362441,2.178538,9.0,2.306615,6.195,7.809,...,103.144456,14.146241,10.457387,-2.737769,15.597470,0.933344,7.696949,0.944992,0.689811,54.181042
1,AFG,Afghanistan,2011,606.694676,0.426355,11.804186,9.0,2.322140,6.094,7.830,...,101.458308,14.146241,10.343973,-2.737769,15.597470,-0.671822,7.501084,-0.573311,0.407955,48.334425
2,AFG,Afghanistan,2012,651.417134,12.752287,6.441213,9.0,2.337911,5.985,7.875,...,99.773131,14.146241,8.677209,-2.737769,15.597470,0.182057,6.759468,0.257318,0.598840,52.293997
3,AFG,Afghanistan,2013,637.087099,5.600745,7.385772,9.0,2.349769,5.879,7.921,...,98.063559,14.146241,8.588138,-2.737769,15.597470,-0.630946,6.904479,-0.543948,0.495654,50.153591
4,AFG,Afghanistan,2014,625.054942,2.724543,4.673996,9.0,2.356536,5.770,7.915,...,96.346394,14.146241,10.702695,-2.737769,15.597470,-1.718797,8.700291,-1.685043,0.466080,49.540119
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1883,ZWE,Zimbabwe,2021,2613.605421,8.468017,98.546105,7.0,3.597974,3.765,9.540,...,83.384953,13.456563,1.148220,42.874299,19.759617,-1.827539,39.891271,-1.356460,1.060306,61.866341
1884,ZWE,Zimbabwe,2022,2536.400502,6.139263,104.705171,7.0,3.608227,3.767,10.087,...,82.547605,12.418930,0.704319,42.321958,23.699220,-0.999621,66.789092,-0.941907,1.238172,65.555881
1885,ZWE,Zimbabwe,2023,2195.224921,5.350869,3.466130,7.0,3.618322,3.724,9.348,...,81.625352,10.023043,0.129141,12.072943,17.117076,-9.451342,76.127228,-9.152526,1.224966,65.281945
1886,ZWE,Zimbabwe,2024,2497.203322,1.742395,3.466130,7.0,3.601654,3.674,9.435,...,80.100412,8.846201,0.519375,10.700213,18.048842,-0.755905,70.380228,0.077595,1.959325,80.514992
1887,ZWE,Zimbabwe,2025,2059.674454,4.734411,3.466130,7.0,3.387457,3.768,9.293,...,86.516840,11.213924,0.656237,8.417171,21.987357,0.081812,43.765490,0.698125,0.449055,49.186967

In [104]:
panel_final.to_csv(
    "fiscal_risk_index.csv",
    index=False
)